rename

diff --git a/.github/workflows/build_amd64.yaml b/.github/workflows/build_amd64.yaml
--- a/.github/workflows/build_amd64.yaml
+++ b/.github/workflows/build_amd64.yaml
@@ -71,8 +71,15 @@ jobs:
         run: |
           ls -l $CONFIG_FILE || echo "Config file not found"
           ls -l $GITHUB_WORKSPACE
-          [ -e $CONFIG_FILE ] && cp -f $CONFIG_FILE $GITHUB_WORKSPACE/$REPO_NAME/
-          mv $GITHUB_WORKSPACE/$REPO_NAME/$CONFIG_FILE $GITHUB_WORKSPACE/$REPO_NAME/.config
+          if [ -e $CONFIG_FILE ]; then
+            cp -f $CONFIG_FILE $GITHUB_WORKSPACE/$REPO_NAME/
+            mv $GITHUB_WORKSPACE/$REPO_NAME/$CONFIG_FILE $GITHUB_WORKSPACE/$REPO_NAME/.config
+            cd $GITHUB_WORKSPACE/$REPO_NAME
+            make oldconfig
+          else
+            echo "Config file $CONFIG_FILE not found. Exiting..."
+            exit 1
+          fi
 
       - name: 7.修改Lan IP
         run: |
